### PR TITLE
update hsqldb to 2.7.1

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>

* Update hsqldb

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by macfarla** [comment]
Getting 3 errors from running `./gradlew :tests:acceptance-test:compileTestJava` locally - to do with something I don't understand in module-info.test 
```
/Users/sallymacfarlane/workspace/tessera/tests/acceptance-test/src/test/java/db/HsqlDatabaseServer.java:4: error: package org.hsqldb.persist is not visible
import org.hsqldb.persist.HsqlProperties;
                 ^
  (package org.hsqldb.persist is declared in module org.hsqldb, but module tessera.acceptance.tests does not read it)
/Users/sallymacfarlane/workspace/tessera/tests/acceptance-test/src/test/java/db/HsqlDatabaseServer.java:5: error: package org.hsqldb.server is not visible
import org.hsqldb.server.Server;
                 ^
  (package org.hsqldb.server is declared in module org.hsqldb, but module tessera.acceptance.tests does not read it)
/Users/sallymacfarlane/workspace/tessera/tests/acceptance-test/src/test/java/db/HsqlDatabaseServer.java:6: error: package org.hsqldb.server is not visible
import org.hsqldb.server.ServerAcl;
                 ^
  (package org.hsqldb.server is declared in module org.hsqldb, but module tessera.acceptance.tests does not read it)
```

**Comment by macfarla** [comment]
with extra work I am down to one error
```

/Users/sallymacfarlane/workspace/tessera/tests/acceptance-test/src/test/java/db/HsqlDatabaseServer.java:4: error: package org.hsqldb.persist is not visible
import org.hsqldb.persist.HsqlProperties;
                 ^
  (package org.hsqldb.persist is declared in module org.hsqldb, which does not export it)
```

**Comment by macfarla** [comment]
^ so in test we are using a class org.hsqldb.persist.HsqlProperties which is not exported by the org.hsqldb module - not sure if there's a way around this

**Comment by macfarla** [comment]
luckily there is an overloaded method that accepts java.util.Properties  and wraps them into HsqlProperties internally.

**Comment by macfarla** [comment]
2.7.1 is out so suppression can be removed

**Comment by macfarla** [comment]
current failures seem to boil down to this 
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jnacl not found, required by tessera.encryption.jnacl
```

**Comment by Krish1979** [comment]
closing this as it is fixed with #1498

**Pull request closed without merging**
