### PR TITLE
Exclude self from unseen parties list in SyncPoller

### PR DESCRIPTION
**Pull request by peterbroadhurst**
Hi Tessera team,

In our Tessera 0.8 environments, the nodes are attempting to connect back to themselves to perform party discovery.

I suspect this is not an issue in most environments, as the HTTPS connection would normally succeed. However, if there is NAT involved the connection fails or times out - resulting in repeated entries in the log as the SyncPoller retries the connection. We don't see a functional issue, just confusing log entries.

We haven't observed this behaviour previously with Constellation.

The attached code change simply filters out the local address from the unseen parties list before it attempts to connect. It removes the connection attempts / log entries in our environments.

### CODE REVIEW

**Comment by prd-fox** [comment]
Hey Peter. This changes look good, thanks for contributing!

Could you fill out our CLA please? Once it's complete we can merge this change.

https://github.com/jpmorganchase/cla/blob/master/cla-2016-09-01.pdf

**Review by melowe — APPROVED** [review]

**Comment by Krish1979** [comment]
Hey Peter

Thanks for the contribution!

We require all contributors to fill out the CLA, as found here:
https://github.com/jpmorganchase/cla

**Comment by peterbroadhurst** [comment]
Thanks @melowe @prd-fox - sorry for the delay getting you the CLA. I've got it signed, and will slack it to you on the Quorum slack

**Comment by prd-fox** [comment]
Linked issue: https://github.com/jpmorganchase/tessera/issues/725

**Pull request merged**
